site_name: Conductor
dev_addr: 172.30.0.218:8000
nav:
nav:
- Home: 'index.md'
- Getting Started: 'guides/getting-started.md'
- Guides: guides.md
- Modules:
  - 'conductor_core': 'conductor_core.md'
  - 'conductor-application-orchestration': 'conductor-application-orchestration.md'
  - 'conductor-aws-s3-filesystem-support': 'conductor-aws-s3-filesystem-support.md'
  - 'conductor-azure-blob-filesystem-support': 'conductor-azure-blob-filesystem-support.md'
  - 'conductor-git-vcs-support': 'conductor-git-vcs-support.md'
  - 'conductor-mysql-database-support': 'conductor-mysql-database-support.md'
  - 'conductor-ssh-support': 'conductor-ssh-support.md'
  - 'Application Support':
    - 'conductor-drupal-platform-support': 'conductor-drupal-platform-support.md'
    - 'conductor-magento-1-platform-support': 'conductor-magento-1-platform-support.md'
    - 'conductor-magento-2-platform-support': 'conductor-magento-2-platform-support.md'
    - 'conductor-wordpress-platform-support': 'conductor-wordpress-platform-support.md'

theme:
      name: mkdocs
extra_css:
    - css/version-select.css
extra_javascript:
    - js/version-select.js
