site_name: Conductor
dev_addr: 172.30.0.218:8000
nav:
- Home: index.md
- Getting Started: guides/getting-started.md
- Guides: guides.md
- Modules:
  - Core: modules/core/index.md
  - Application Orchestration: modules/application-orchestration.md
  - Platform Support:
    - Drupal 8: modules/platform-support/drupal-8.md
    - Magento 1: modules/platform-support/magento-1.md
    - Magento 2: modules/platform-support/magento-2.md
    - Wordpress: modules/platform-support/wordpress.md
  - Filesystem Support:
    - AWS (Amazon Web Services): modules/filesystem-support/aws.md
    - Microsoft Azure: modules/filesystem-support/microsoft-azure.md
    - SFTP: modules/filesystem-support/sftp.md
  - Database Support:
    - MySQL: modules/database-support/mysql.md
  - Shell Support:
    - SaltStack: modules/shell-support/salt-stack.md
    - SSH: modules/shell-support/ssh.md
  - VCS Support:
    - Git: modules/vcs-support/git.md

theme:
  name: mkdocs
extra_css:
- css/version-select.css
extra_javascript:
- js/version-select.js

module_path_map:
  core: core

